
<h2>Data use</h2>

<div class="row">
    <div class="col-xs-12">


    <h3>POLICIES AND PLAN FOR DATA IN THE T2D KNOWLEDGE PORTAL</h3>
    <p>
        The Broad Institute will serve as the Data Coordinating Center (DCC) for AMP-T2D. On behalf of AMP-T2D, the DCC will aggregate data, support analyses, and continue to update
        capabilities to disseminate results relevant to the genetics of T2D (T2D) and related traits, while coordinating collaboration within the AMP-T2D Project.
    </p>

    <p>
        Additionally, a key objective of the AMP T2D Project is to merge global data while maintaining compliance with regional data privacy regulations.
        Thus the FNIH aims to fund an organization(s) to build and maintain a federated node (or nodes) for the Knowledge Portal outside of the United States that
        will contribute data and query results to the Knowledge Portal while maintaining compliance with regional data privacy regulations. At least one node
        (that could potentially serve as a hub for other nodes) will preferably consist of a technical replicate of the Knowledge Portal currently being developed
        under other NIH/FNIH funded initiatives. This site(s) will also work in partnership with funding organizations and other funded parties such that proposed
        solutions comply with data harmonization methods, data processing methods, technical details, and data release policies being developed for the Knowledge Portal.
    </p>

    <p>
        The next set of sections of this document outline the Data Aggregation and Resource Distribution at the DCC. As the Federated nodes are funded, we will expand
        this document to include the processes for data aggregation at these sites. However, the policies and plan for Data Release and Use of Results outlined at the
        end of this document will apply to both data coming to the DCC and the Federated nodes.
    </p>

    <h4>Data Aggregation and Resource Distribution at the DCC</h4>

    <p>
        As the DCC for the AMP-T2D Consortium, the Broad Institute (along with its AMP funded partners) intends to (a) serve as the gateway to a large (and growing) aggregation of
        data relevant to the genetics of T2D and its complications; (b) automate analyses required to interpret those data; and (c) communicate results to diverse audiences via
        presentation and publication. Each of these goals involves distinct categories of resources and activities that we will share and/or manage:
    </p>

    <h4>
        Data Aggregation
    </h4>

    <p>
        We will aggregate data on behalf of AMP-T2D. Data aggregated under this effort will not be generated by the knowledge Portal development work funded through the Portal-specific grants,
        but rather obtained from other investigators and repositories who wish to collaborate on and contribute to this effort, including other investigators funded by the wider AMP-T2D program.
        Moreover, the role of the Portal will not be to redistribute individual-level data, but rather to generate results attained via standard and customized queries that can be widely shared
        with the scientific community. Because the primary, individual-level data are neither generated by this project, nor redistributed to other users, the role of the Portal is limited to
        secure intake, storage and management, automated analyses, and dissemination of results in summary (i.e., not individual-level) form while complying with intended use of the data and all
        relevant regulations.
    </p>

    <p>
        We will focus on three classes of data: individual-level genotypes, individual-level phenotypes, and external precomputed results or annotations (e.g., results from individual
        studies or meta-analyses of multiple studies, processed annotations).
    </p>

    <p>
        The data and results currently stored in the Portal have either been generated at the Broad Institute as part of IRB-approved secondary use protocols or, in the case of
        meta-analysis results from published genome-wide association study (GWAS) datasets, obtained in such a form that Broad was determined to be “not engaged in human subjects
        research” (per the criteria described in the U.S. Health and Human Services Office for Human Research Protections’ 2008 Guidance on Engagement of Institutions in Human
        Subjects Research, under criterion #7; see also http://www.hhs.gov/ohrp/policy/cdebiol.pdf). All data have been de-identified prior to being sent to Broad; at no time or
        under no circumstances will investigators funded by this grant have information linking data back to subject identifiers.
    </p>

    <p>
        For datasets subsequently added to the Portal, raw data will be obtained through formal NIH systems for data-sharing such as dbGaP, or directly from investigators who
        collected the data. It will be the decision of NIH and the AMP-T2D Steering Committee whether to accept into the Portal data that are not in dbGaP and, if so, the terms
        on which the data can be made accessible for analyses by other parties. At the DCC, we will develop software for storing and managing datasets, and will not redistribute
        the raw data to third parties. For bulk data (e.g., raw and harmonized individual-level genotype data), we will use object storage systems, with access controlled through
        application programming interfaces (APIs). Only authenticated and authorized users can access data; all such access is logged and auditable.
    </p>

    <p>
        The Portal will contain both publicly available datasets retrieved from public sources and data generated directly by investigators. In the case of datasets coming into
        the portal directly from publicly available databases (ie. dbGAP and EGA), the DCC will be tasked with aggregating the data and ensuring the necessary QCs are completed
        on the phenotype and genetic data before the data is available on the portal. Investigators submitting their data directly to the DCC will be responsible for ensuring
        that all incoming data is in the supplied in the appropriate formats.
    </p>

    <p>
        Additionally, we are currently building a database tool that captures data use restrictions for each dataset electronically using an ontology-based consent database, and
        can match those restrictions against potential research usage to ensure that only appropriate users can query specific datasets. Web-based tools, currently in development,
        support both the entry of data-use restrictions and the review of access requests.  This will enable the aggregation of additional and more diverse datasets for the Portal.
    </p>

        <h4>Examples of datasets</h4>

        <p>
            <ol>
                <li>Current and future genetic studies of T2D:</li>
                <ul>
                    <li>Exomes from the consortia T2D-GENES, GoT2D, LuCAMP, SIGMA, ESP</li>
                    <li>Genomes from T2D-GENES Project 2 and GoT2D</li>
                    <li>Other datasets to be generated as part of the AMP-T2D collaboration</li>
                    <li>Any other relevant datasets contributed by members of the research community</li>
                </ul>

                <li>Current and future genetic studies of related quantitative traits</li>
                <ul>
                    <li>GWAS/Exome array results, DIAGRAM, MAGIC, GUARDIAN, etc.</li>
                </ul>

                <li>Current and future studies of T2D-related complications</li>
                <ul>
                    <li>Genetic and phenotypic information from studies collecting outcome data on complications such as myocardial infarction, diabetic kidney disease, diabetic retinopathy, non-alcoholic steatohepatitis, etc.</li>
                </ul>

                <li>Annotations of function</li>
                <ul>
                    <li>Gene expression</li>
                    <li>Chromatin and epigenetic; transcription factor binding; and evolutionary conservation</li>
                </ul>

            </ol>
        </p>


    <h4>Classes of datasets for storage and analysis in the Portal</h4>

        <p>
        <ol>
            <li>Those that <strong>do not require</strong> ethical and regulatory approval</li>
            <ul>
                <li>Results from publicly available datasets</li>
                <li>Summary statistics</li>
                <li>De-identified individual level genetic and phenotypic data generated externally</li>
                <li>Any other relevant datasets contributed by members of the research community</li>
            </ul>
            <li>Those that <strong>require</strong> approval from public access sites</li>
            <ul>
                <li>Access controlled export (dbGaP, etc.) of individual level data where we will serve results and summary statistics</li>
            </ul>
            <li>Those that <strong>require</strong> IRB approval</li>
            <ul>
                <li>Generated directly at the Broad on de-identified DNA samples</li>
            </ul>
            <li>Those that <strong>require</strong> a Data Transfer Agreement (DTA)</li>
        </ol>
    </p>


    <h4>Data Transfer Agreement</h4>
    <p>
        For all de-identified individual-level genetic and phenotypic data generated externally (genotype, phenotypes, annotations, etc.) received by the Broad Institute as DCC for the AMP-T2D
        Knowledge Portal, we will execute a Data Transfer Agreement (DTA) with the submitting institution. We will ensure that the usage of the data is compliant with the Data
        Use Restrictions associated with the dataset. It will be the responsibility of the submitting institution to outline the Data Use Restrictions for the data coming to the
        DCC for the Knowledge Portal.
    </p>

    <p>
        The data will never be shared with Portal users; only results will be shared. The individual-level and summary data will reside in one or several data vaults behind a secure
        firewall. User-activated analytical modules will be deployed behind the firewall to analyze the data or query precomputed results. The Portal will provide results in
        response to queries for information, obtained from genetic analyses performed on the data. The purpose of the AMP-T2D web Portal will be to enable broad access to the
        comprehensive results of genetic studies of T2D, related traits, and diabetic complications. To ensure that the web Portal is effective in allowing access to results and
        data –- both within AMP-T2D and with the broader biomedical research community –- we will develop an interface to provide access to results in a form designed to meet user
        needs while maintaining the individual data privacy requirements, and will engage Portal users in assessing the value of these features.
    </p>

    <p>
        Results from studies included in the Portal will be available genome-wide (i.e., not limited to "top hits"), and results from different studies and types will be integrated
        and presented simultaneously. Metadata and other technical details (e.g., analysis parameters, explanations of terms, documentation of methods) will be available at lower levels of drilldown.
    </p>

    <p>
        If you would like to review a copy of our DTA, please <a href='${createLink(controller:"informational", action:"sharingPolicy")}'>click here</a>
    </p>


    <h4><u>Resource Distribution and Sharing</u></h4>

    <p>
        We will share software, methods, and code developed as part of consortium efforts. Specifically, we envision three types of sharing: (a) sharing of software source code;
        (b) sharing services; and (c) sharing of effort between groups with the intention of maintaining or extending existing software.
    </p>

    <h4>Sharing of software source code</h4>

    <p>
        We are producing open-source software under the terms of the BSD 3 open-source license (see <a href="http://opensource.org/licenses/BSD-3-Clause">http://opensource.org/licenses/BSD-3-Clause</a>).
        As such, this code will be
        freely available for use by any other parties; the software will be supplied “AS IS” with no implied warranty or promises of support. We will maintain a
        Github repository from which interested parties can download the source code.
    </p>

    <h4>Sharing services</h4>

    <p>
        Our software will be constructed as a distributed system in which computers communicate using standard protocols (HTTP for transport, with REST as an organizing principle and data
        payloads defined with JSON), with well-defined interfaces specific to the computational topics addressed by each computer system. These services will in principle be accessible by
        any other party willing to adopt the conventions used by our services. To the extent that data on these services may be under privacy and use restrictions, these running services will
        be designed to provide information only in forms that protect privacy and security, or in secure, encrypted mode for other parties with permission to access and receive the information.
    </p>

    <h4>Sharing of effort between groups to maintain or extend existing software</h4>

    <p>
        The Portal architecture will be designed to facilitate front-end contributions (e.g., extensions of existing widgets for data exploration) from a wide community of developers.
        Data or computations for REST servers will be encapsulated as loosely coupled “plug-in” modules that may be written in different languages (e.g., Python, JVM-based languages,
        shell scripting). This approach anticipates the contribution of computational modules from other individuals and groups, both within and outside of the AMP consortium.
    </p>


    <h4><u>Policies for Data Release</u></h4>

    <h4>Data processing and availability (applicable for both data coming to DCC and to Federated nodes)</h4>

    <ol>
        <li><u>Data Deposit</u>: The DCC (and Federated nodes) will receive data from submitters on an ongoing basis. The Data
        deposition stage has several components that must be completed for the data to be ready for release into the Portal. These are: </li>
        <ol>
            <li>Data use agreements and ethical approvals for data transfer to DCC (or the Federated nodes) and release into Portal.</li>
            <li>Physical transfer of data and all meta-data, in required formats, into Data Intake System at the DCC (or at a Federated node).</li>
            <li>De-identified individual level genetic and phenotypic data generated externally</li>
            <li>Data storage, curation, QC, and harmonization of submitted data performed by the DCC.</li>
        </ol>

        <p>
            In general, upon depositing data into the Portal, a QC filter on genotypes and phenotypes will be deployed by the DCC as per standard operating procedures in the field. Data will only be available after these initial filters and project sanctioned analyses are applied. Filters will include automated steps and final human curation, as determined by the AMP-T2D investigative team.
        </p>

        <li><u>Early-Access Period</u>: After the Data Deposition steps are complete, data will be released to the Portal. This denotes the start of the Early
        Access Period.  This 6-month time period will be divided into 2 phases. The first 3 months will be the Early Access Phase 1 window where data
        are available on the portal to all users. At this point, project sanctioned QC and analyses have been performed, but the data are NOT considered
        final or fully integrated on the Portal. The goal of the Early Access Phase 1 time period is to allow users to review the data, to perform additional
        QC and analyses, and to finalize and integrate the dataset. At the end of the first 3 months, the data will move to the Early Access Phase 2, where
        data are considered final and fully integrated. During these last 3 month of Early Access Phase the AMP</li>

        <p>
            During this 6-month period, all analyses, results, and publications proposed are subject to the “Fort Lauderdale Principles” articulated for the sharing of genomic data
            (<a href="http://www.wellcome.ac.uk/stellent/groups/corporatesite/@policy_communications/documents/web_document/wtd003207.pdf">http://www.wellcome.ac.uk/stellent/groups/corporatesite/@policy_communications/documents/web_document/wtd003207.pdf</a>).
        </p>

        <li><u>Open-Access Period</u>: After 6-months, the Early Access Period (phase 1 and 2) ends, and there is Open Access to the finalized and fully integrated datasets. The results from analyses on the data are now freely available for use in publications, based on the terms of User Responsibilities and Citing Guidelines.</li>
    </ol>

    <h4>Data release timeline:</h4>

    <img src="../static/images/dataReleaseTimeline.png"/>

    <h4><u>Accessing the Portal and Terms of Conduct</u></h4>

    <p>
        The following polices are listed on the Portal and each user who logs on will be required to read these terms and click an acknowledgement of conduct before accessing the Portal:
    </p>

    <h4>User registration</h4>

    <p>
        To access the Portal, users must obtain a Google ID, which will be used for quality control (QC) and monitoring purposes (see below).
    </p>

    <h4>Data use and availability</h4>

    <p>
        All users are welcome to use results from analyses of the data in the Portal to further their research without seeking explicit permission from the Portal team or funders.
        Users are also welcome to cite data in scientific publications, provided that they cite the Portal as the source. If users are citing a single dataset represented in the Portal,
        they should cite both the Portal and the relevant paper for that dataset (if one has been published).
    </p>

    <h4>User Responsibilities</h4>

    <p>
        Portal users are expected to abide by the following provisions on data use:
    </p>

    <ol>
        <li>
            Users will not attempt to download any dataset in bulk from the Portal
        </li>
        <li>
            Users will not attempt to identify or contact research participants
        </li>
        <li>
            Users will protect data confidentiality
        </li>
        <li>
            Users will not share any of the data with unauthorized users
        </li>
        <li>
            Users will report any inadvertent data release, security breach, or other data management incidents of which they become aware
        </li>
        <li>
            Users will abide by all applicable laws and regulations for handling genomic data
        </li>
        <li>
            Users will not submit a manuscript for publication until the Early Access Period is over (6 months after the clean dataset becomes available in the Portal),
            to allow for beta testing on the integrity of the dataset, finalization of the results on the Portal, and for the AMP Consortium and data submitters to analyze
            and submit publications during this period.
        </li>
    </ol>

    <p>
        Agreeing to these provisions is a requirement of Portal use. Violating them may result in an NIH investigation and sanctions including revocation of access to the Portal.
    </p>

    </div>

</div>
