
<h2>Data use</h2>

<div class="row">
    <div class="col-xs-12">



        <h3>POLICIES AND PLAN FOR DATA IN THE T2D KNOWLEDGE PORTAL</h3>
        <p>
            The Broad Institute will serve as the Data Coordinating Center (DCC) for AMP-T2D. On behalf of AMP-T2D, the DCC will aggregate data,
            support analyses and continue to update capabilities to disseminate results relevant to the genetics of type 2 diabetes and related traits,
            while coordinating collaboration within the AMP-T2D Project.
        </p>

        <h4>Data and Resource Aggregation and Distribution</h4>

        <p>
            As the DCC for the AMP-T2D Consortium, the Broad Institute (along with its AMP funded partners) intends to (a) serve as the gateway to a large (and growing) aggregation of  data relevant to the genetics of type 2 diabetes and its complications; (b) automate analyses required to interpret those data; (c) communicate results to diverse audiences via presentation and publication.
            Each of these goals involves distinct categories of resources that we will share and/or manage:
        </p>

        <h4>
            Data Aggregation
        </h4>

        <p>
            We will aggregate data on behalf of AMP-T2D. Data aggregated under this effort are not to be generated by the knowledge Portal development work funded through the Portal-specific grants, but rather obtained from other investigators and repositories who wish to collaborate on and contribute to this effort, including other
            investigators funded by the wider AMP-T2D program. Moreover, the role of the Portal will not be to redistribute individual-level data, but rather to generate results attained via customized queries that can be
            widely shared with the scientific community. Because the data are neither generated by this project, nor redistributed to other users, the role of the Portal is limited to secure intake, storage and management, automated analyses, and dissemination of results in summary (i.e., not individual-level) form while complying with intended use of the data and all relevant regulations.
        </p>
        <p>
            We will focus on three classes of data: individual-level genotypes, individual-level phenotypes, and external precomputed results or annotations (e.g., results from meta-analyses, processed annotations).
        </p>
        <p>
            The data and results currently stored in the Portal have either been generated at the Broad Institute as part of IRB-approved secondary use protocols or, in the case of meta-analysis results from published GWAS datasets, obtained in such a form that Broad was determined to be “not engaged in human subjects research” (per the criteria described in the U.S. Health and Human Services Office
            for Human Research Protections’ 2008 Guidance on Engagement of Institutions in Human Subjects Research, under criterion #7; see also http://www.hhs.gov/ohrp/policy/cdebiol.pdf). All data have been de-identified prior to being sent to Broad; at no time or situation will investigators funded under this grant have information linking data back to subject identifiers.
        </p>
        <p>
            For datasets subsequently added to the Portal, raw data will be obtained through formal NIH systems for data-sharing such as dbGaP, or from investigators who collected the data. It will be the decision of NIH and the AMP-T2D Steering Committee whether to accept into the Portal data that is not in dbGAP and, if so, the terms
            on which it can be made accessible for analyses by other parties. At the DCC, we will develop software for storing and managing datasets, and will not redistribute the raw data to third parties. For bulk data (e.g., raw and harmonized individual-level genotype data), we will use object storage systems, with access controlled
            through application programming interfaces (APIs). Only authenticated and authorized users can access data; all such access is logged and auditable.
        </p>

        <p>
            Our database tool Prometheus also captures data use restrictions for each dataset electronically using an ontology-based consent database, and can match those restrictions against potential research usage to ensure that only appropriate users can query specific datasets. Web-based tools, currently in development, support both the entry of data-use restrictions and the review of access requests.
        </p>

        <h4>Examples of Datasets:</h4>

        <p>
            <ol>
                <li>Current and future genetic studies of type 2 diabetes:</li>
                <ul>
                    <li>Exomes from the consortia T2D-GENES, GoT2D, LuCAMP, SIGMA, ESP</li>
                    <li>Genomes from T2D-GENES Project 2 and GoT2D</li>
                    <li>Other datasets to be generated as part of the AMP-T2D collaboration</li>
                    <li>Any other relevant datasets contributed by members of the research community</li>
                </ul>
                <li>Current and future genetic studies of related quantitative traits</li>
                <ul>
                    <li>GWAS/Exome array results, DIAGRAM, MAGIC, GUARDIAN, etc.</li>
                </ul>
                <li>Current/future studies of type 2 diabetes-related complications</li>
                <ul>
                    <li>Genetic and phenotypic information from studies collecting outcome data on complications (such as myocardial infarction, diabetic kidney disease, diabetic retinopathy, non-alcoholic steatohepatitis)</li>
                </ul>
                <li>Annotations of function</li>
                <ul>
                    <li>Gene expression</li>
                    <li>Chromatin and epigenetic; transcription factor binding; and evolutionary conservation</li>
                </ul>

            </ol>
        </p>

<p>
    Classes of datasets for storage and analysis in the Portal
</p>

        <p>
        <ol>
            <li>Those that do not require ethical and regulatory approval</li>
            <ul>
                <li>Results from publicly available datasets</li>
                <li>Summary statistics</li>
                <li>De-identified individual level genetic and phenotypic data generated externally</li>
                <li>Any other relevant datasets contributed by members of the research community</li>
            </ul>
            <li>Those that require approval from public access sites</li>
            <ul>
                <li>Access controlled export (dbGaP, etc.) of individual level data where we will serve results and summary statistics</li>
            </ul>
            <li>Those that require IRB approval</li>
            <ul>
                <li>Generated directly at the Broad on de-identified DNA samples</li>
            </ul>
            <li>Those that require a Data Transfer Agreement (DTA)</li>
        </ol>
    </p>

 <h4>Data Transfer Agreement</h4>
        <p>For all de-identified individual level genetic and phenotypic data generated externally (genotype, phenotypes, annotations, etc.) received by the Broad Institute as DCC for the AMP-T2D Knowledge Portal, we will execute a DTA with the submitting institution. We will ensure that the usage of the data is compliant with the Data Use Restrictions associated with the dataset. It will be the responsibility of the submitting institute to outline the Data Use Restrictions for the data coming to the DCC for the Knowledge Portal.
        </p>
        <p>The data will never be shared with users of the Portal: only results. The individual-level and summary data will reside in one or several data vaults behind a secure firewall. User-activated analytical modules will be deployed behind the firewall to analyze the data or query precomputed results. The Portal will provide results in response to queries for information, obtained from genetic analyses performed on the data. The purpose of the AMP-T2D web Portal will be to enable broad access to the comprehensive results of genetic studies of type 2 diabetes, related traits, and diabetic complications. To ensure that the web Portal is effective in allowing access to results and data – both within AMP-T2D and with the broader biomedical research community – we will develop an interface to provide access to results in a form designed to meet user needs while maintaining the individual data privacy requirements, and will engage Portal users in assessing the value of these features.
        </p>
        <p>Results from studies included in the Portal will be available genome-wide (i.e., not limited to "top hits"), and results from different studies and types will be integrated and presented simultaneously. Metadata and other technical details (e.g., analysis parameters, explanations of terms, documentation of methods) will be available at lower levels of drilldown.
        </p>
        <p>f you would like to review a copy of our DTA,
        then a link will be made publicly available.
        %{--please click here (INSERT LINK) --}%
        </p>

        <h4>Resource Sharing</h4>
        <p>We will share software, methods, and code developed as part of consortium efforts. Specifically, we envision three types of sharing: (a) sharing of software source code; (b) sharing services; and (c) sharing of effort between groups with the intention of maintaining or extending existing software.
        </p>
        <p>Sharing of software source code: We are producing open-source software under the terms of the BSD 3 open-source license (see http://opensource.org/licenses/BSD-3-Clause). As such, this code will be freely available for use by any other parties; the software will be supplied “AS IS” with no implied warranty or promises of support. We will maintain a Github repository from which interested parties can download the source code.
        </p>
        <p>Sharing services: Our software will be constructed as a distributed system in which computers communicate using standard protocols (HTTP for transport, with REST as an organizing principle and data payloads defined with JSON), with well-defined interfaces specific to the computational topics addressed by each computer system. These services will in principle be accessible by any other party willing to adopt the conventions used by our services. To the extent that data on these services may be under privacy and use restrictions, these running services will be designed to provide information only in forms that protect privacy and security, or in secure, encrypted mode for other parties with permission to access and receive the information.
        </p>
        <p>Sharing of effort between groups to maintain or extend existing software: The Portal architecture will be designed to facilitate front-end contributions (e.g., extensions of existing widgets for data exploration) from a wide community of developers. Data or computations for REST servers will be encapsulated as loosely coupled “plug-in” modules that may be written in different languages (e.g., Python, JVM-based languages, shell scripting). This approach anticipates the contribution of computational modules from other individuals and groups, both within and outside of the AMP consortium.
        </p>


        <h4>Policies for accessing the Portal and Terms of Conduct</h4>
        <h4>The following polices are listed on the Portal and each user who logs on will be required to read these terms and click an acknowledgement of conduct before accessing the Portal. </h4>

        <p>

        </p>
        <h4>Data use and availability</h4>
        <p>All users are welcome to use any data in the Portal to further their research without seeking explicit permission from the Portal team or funders. Users are also welcome to cite data in scientific publications, provided that they cite the Portal as the source. If users are citing a single dataset represented in the Portal, we encourage them to cite both the Portal and the relevant paper for that dataset (if one has been published).
        </p>
        <h4>User registration</h4>
        <p>To access the Portal, users must obtain a Google ID, which will be used for quality control and monitoring purposes (see below). A more stringent registration process, requiring identification of the user and institutional affiliation, will be required in instances where the analyses requested might lead to the return of results where de-identified individual-level data could be extracted.
        </p>
        <h4>Data processing and availability        </h4>
         <p>Upon depositing data into the Portal, a quality control filter on genotypes and phenotypes will be deployed as per standard operating procedures in the field. Data will not be immediately available until these initial filters are applied. Filters will include automated steps and final human curation, as determined by the investigative AMP-T2D team.
         </p>
        <p>Once clean data are released into the Portal for analyses, they will still remain in “draft” mode for beta testing. This denomination will be applied for a period of at least 3 months to allow for the integration and analyses of new datasets with existing data, at which time additional quality control issues might be uncovered. Users are welcome to analyze draft datasets, but they should use caution and ensure that results obtained during the beta testing period reproduce when using the finalized dataset.
        </p>
        <p>Once a dataset passes the beta testing period it will be labeled as finalized. An additional embargo period of 3 months will be required before submission of a manuscript for publication using newly deposited datasets. These policies are consistent with the “Fort Lauderdale Principles” articulated for the sharing of genomic data (INSERT HYPERLINK http://www.wellcome.ac.uk/stellent/groups/corporatesite/@policy_communications/documents/web_document/wtd003207.pdf).
        </p>

        <h4>User responsibilities</h4>
        Portal users are expected to abide by the following provisions on data use:
        <ol>






        <li>Users will not attempt to download any dataset in bulk from the Portal</li>
        <li>Users will not attempt to re-identify or contact research participants</li>
        <li>Users will protect data confidentiality</li>
        <li>Users will not share any of the data with unauthorized users</li>
        <li>Users will report any inadvertent data release, security breach or other data management incidents of which Users become aware
        </li>
        <li>Users will abide by all applicable laws and regulations for handling genomic data</li>
        <li>Users will not attempt submission of a manuscript for publication until 6 months after a clean dataset becomes available in the Portal, to allow for beta testing on the integrity of the dataset and the embargo period required by data submitters.
        </li>
    </ol>
        <p>Agreeing to these provisions is a requirement of Portal use. Violating them may result in an NIH investigation and sanctions including revocation of access to the Portal.
        </p>



        <p>
            <h4><a href='${createLink(controller:"informational", action:"sharingPolicy")}'>AMP data use policy</a></h4>
         </p>



    </div>

</div>
